const UI_LABELS: Record<string, string> = {
  active: "Activo",
  inactive: "Inactivo",
  suspended: "Suspendido",
  draft: "Borrador",
  pending: "Pendiente",
  pending_approval: "Pendiente de aprobación",
  pending_deletion: "Pendiente de desactivación",
  submitted: "Enviado",
  resubmitted: "Reenviado",
  under_review: "En revisión",
  correction_requested: "Corrección solicitada",
  approved: "Aprobado",
  rejected: "Rechazado",
  scheduled: "Programado",
  assigned: "Asignado",
  en_route: "En ruta",
  delivered: "Entregado",
  partially_delivered: "Entregado parcialmente",
  not_delivered: "No entregado",
  rescheduled: "Reprogramado",
  paid: "Pagado",
  partial: "Parcial",
  cancelled: "Anulado",
  voided: "Anulado",
  confirmed: "Confirmado",
  refunded: "Reembolsado",
  available: "Disponible",
  occupied: "Ocupado",
  cleaning: "En limpieza",
  maintenance: "Mantención",
  out_of_service: "Fuera de servicio",
  checked_in: "Ingreso registrado",
  checked_out: "Salida registrada",
  current: "Al día",
  overdue: "Vencido",
  normal: "Normal",
  urgent: "Urgente",
  low: "Baja",
  medium: "Media",
  high: "Alta",
  cash: "Efectivo",
  transfer: "Transferencia",
  bank_transfer: "Transferencia bancaria",
  card: "Tarjeta",
  check: "Cheque",
  credit: "Crédito",
  mixed: "Mixto",
  petty_cash: "Caja chica",
  checking: "Cuenta corriente",
  sight: "Cuenta vista",
  savings: "Cuenta de ahorro",
  vista: "Cuenta vista",
  rut: "Cuenta RUT",
  sequential: "Secuencial",
  parallel: "Paralelo",
  supplier_payment: "Pago a proveedor",
  supplier: "Proveedor",
  reimbursement: "Reembolso",
  advance: "Anticipo",
  other: "Otro",
  edit: "Edición",
  deactivate: "Desactivación",
  approved_with_observations: "Aprobado con observaciones",
  total: "Total",
  refund: "Reembolso",
  deposit: "Abono",
  operational: "Consumo operacional",
  loss: "Falla o pérdida",
  verified: "Verificada",
  unverified: "No verificada",
  observed: "Observado",
  created: "Creado",
  updated: "Actualizado",
  deleted: "Eliminado",
  activate: "Activación",
  restart_all: "Reiniciar todo",
  resume_current: "Continuar desde la etapa actual",
  submit: "Envío a aprobación",
  resubmit: "Reenvío a aprobación",
  approve: "Aprobación",
  reject: "Rechazo",
  request_correction: "Solicitud de corrección",
  schedule: "Programación",
  execute_payment: "Pago ejecutado",
  payment_request: "Solicitud de pago",
  petty_cash_report: "Rendición de caja chica",
  inventory_material: "Material de inventario",
};

/**
 * Traduce valores persistidos para mostrarlos al usuario sin modificar las
 * claves que consumen la base de datos, las rutas o las reglas de negocio.
 */
export function uiLabel(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  const text = String(value);
  return UI_LABELS[text] ?? text.replaceAll("_", " ");
}

export function uiLabels(values: readonly string[]) {
  return values.map((value) => ({ value, label: uiLabel(value) }));
}
