import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader, Panel } from "@/components/ui/page";
import { StatusBadge } from "@/components/finance/status-badge";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireSession } from "@/modules/platform/auth/application/session";
import { clp, formatWeek } from "@/modules/finance/petty-cash/domain/petty-cash";

export default async function PettyCashReviews({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const ctx = await requireSession(); if (!ctx.permissions.has("finance.petty_cash.review")) redirect("/no-access"); const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const size = 10;
  const supabase = await createSupabaseServerClient(); let query = supabase.from("petty_cash_reports").select("id,report_number,status,total_registered,total_lines,week_start,week_end,submitted_at,business_unit_id,business_units(name),profiles!petty_cash_reports_responsible_id_fkey(first_name,last_name)", { count: "exact" }).in("status", params.status ? [params.status] : ["submitted", "resubmitted", "under_review"]).is("deleted_at", null);
  if (params.unit) query = query.eq("business_unit_id", params.unit); if (params.worker) query = query.eq("responsible_id", params.worker); if (params.week) query = query.eq("week_start", params.week); if (params.min) query = query.gte("total_registered", Number(params.min)); if (params.max) query = query.lte("total_registered", Number(params.max)); if (params.q) query = query.ilike("report_number", `%${params.q}%`);
  const { data, count } = await query.order("submitted_at", { ascending: params.sort === "oldest" }).range((page - 1) * size, page * size - 1); const pages = Math.max(1, Math.ceil((count ?? 0) / size));
  return <><PageHeader title="Bandeja de revisión" description="Rendiciones pendientes de las unidades que tienes asignadas." eyebrow="Finanzas · Caja Chica" /><Panel><form className="grid gap-2 md:grid-cols-3 xl:grid-cols-6"><input name="q" defaultValue={params.q} placeholder="Correlativo" className="rounded-xl border p-2.5 text-sm" /><select name="unit" defaultValue={params.unit} className="rounded-xl border p-2.5 text-sm"><option value="">Todas las unidades</option>{ctx.units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select><input name="week" type="date" defaultValue={params.week} className="rounded-xl border p-2.5 text-sm" /><input name="min" type="number" placeholder="Monto mínimo" defaultValue={params.min} className="rounded-xl border p-2.5 text-sm" /><input name="max" type="number" placeholder="Monto máximo" defaultValue={params.max} className="rounded-xl border p-2.5 text-sm" /><button className="rounded-xl bg-[#173f2d] px-4 text-sm font-semibold text-white">Filtrar</button></form></Panel><Panel className="mt-4"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="text-xs uppercase text-slate-500"><th className="pb-3">Correlativo</th><th>Trabajador</th><th>Unidad</th><th>Semana</th><th>Líneas</th><th>Total</th><th>Estado</th><th>Enviada</th><th /></tr></thead><tbody>{data?.map((report) => { const profile = one<{ first_name?: string; last_name?: string }>(report.profiles); const unit = one<{ name?: string }>(report.business_units); return <tr key={report.id} className="border-t"><td className="py-4 font-semibold">{report.report_number}</td><td>{profile?.first_name} {profile?.last_name}</td><td>{unit?.name}</td><td>{formatWeek(report.week_start, report.week_end)}</td><td>{report.total_lines}</td><td>{clp(report.total_registered)}</td><td><StatusBadge value={report.status} /></td><td>{report.submitted_at ? new Date(report.submitted_at).toLocaleDateString("es-CL") : "—"}</td><td><Link href={`/finance/petty-cash/reviews/${report.id}`} className="font-semibold text-[#277a55]">Revisar</Link></td></tr>; })}</tbody></table></div>{!data?.length && <p className="py-12 text-center text-sm text-slate-500">No hay rendiciones pendientes.</p>}<div className="mt-4 flex justify-between border-t pt-4 text-sm"><span>Página {page} de {pages} · {count ?? 0} registros</span><div className="flex gap-2">{page > 1 && <Link href={{ query: { ...params, page: page - 1 } }} className="rounded-lg border px-3 py-1.5">Anterior</Link>}{page < pages && <Link href={{ query: { ...params, page: page + 1 } }} className="rounded-lg border px-3 py-1.5">Siguiente</Link>}</div></div></Panel></>;
}
function one<T>(value: unknown): T | undefined { return (Array.isArray(value) ? value[0] : value) as T | undefined; }
